## NumPy: (Numerical Python) is a Python library mainly used for numerical calculations and working with arrays.

In [107]:
print("Hello")

Hello


In [108]:
 #! pip install numpy
import numpy as np

In [109]:
 #? array --> ndarray => array object in NumPy
#? array()

In [110]:
 #! 0 Dimension
a=np.array(57)
# print(a)
  # or
a

array(57)

In [111]:
ar=np.array([2,3,4,56])
# ar
type(ar)

numpy.ndarray

In [112]:
 #! Checking Dimension
#! Attribute used => ndim
ar.ndim


1

In [113]:
 #! Checking Datatype
#! => dtype
ar.dtype

dtype('int64')

In [114]:
 #! 2 Dimension -> Matrix
#? 2 x 3
arr=np.array([[1,2,3],[5,6,7]])
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [115]:
 #? 4 x 5
m=np.array([[1,2,3,4,5],[6,7,8,9,5],[7,4,6,3,2],[2,46,7,44,5]])
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  5],
       [ 7,  4,  6,  3,  2],
       [ 2, 46,  7, 44,  5]])

In [116]:
 #! Checking shape or order of an array 
# ! => shape
m.shape

(4, 5)

In [117]:
 #! 3 Dimension
arr_1=np.array([[[1,2,3],[4,5,6]],
                [[2,4,6],[6,7,1]]
                ])
arr_1
# arr_1.ndim
# arr_1.shape


array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 4, 6],
        [6, 7, 1]]])

In [118]:
 #! Checking Size => size-> Total no.of elements
arr_1.size

12

In [119]:
 #? Create a zero matrix of 2 x 5
#! zeros()
arr_2=np.zeros((2,5),dtype=int)   #? change from float to int
arr_2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [120]:
 #! Ones() -> Matrix with entries 1
arr1=np.ones((6,8),dtype=int)
arr1

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [121]:
 #? In 3 Dimension specify the matrix number also  =>  (mat_number,m,n)
#? 3 matrix with 2 x 4 order
arr2=np.ones((3,2,4),dtype=int)
arr2

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [122]:
 #! full() -> To create constant array
arr4=np.full((5,6),8,dtype=int)
arr4


array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [123]:
 #! Diagonal matrix

# 1 0 0
# 0 2 0
# 0 0 3

In [124]:
 #! Identity matrix

# 1 0 0
# 0 1 0
# 0 0 1

In [125]:
 #! eye() -> To create an identity matrix 
arr6=np.eye(3,dtype=int)
arr6

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [126]:
 #! arange() -> Used to create evenly spaced values within a range ---- (start,stop,step)
np.arange(25,39,2)

array([25, 27, 29, 31, 33, 35, 37])

In [127]:
 #! linspace(start,stop,no.of.values)
np.linspace(1,10,5,dtype=int)
#* type will be in float

array([ 1,  3,  5,  7, 10])

In [128]:
 #! random ->Rturns random values
#? 1: rand(rows,columns)
np.random.rand(3,8)

array([[0.66943787, 0.38160258, 0.34614762, 0.85228702, 0.48912391,
        0.58084841, 0.30375878, 0.66304484],
       [0.9819199 , 0.10126928, 0.24536189, 0.61077352, 0.29223097,
        0.02938668, 0.95444797, 0.81665371],
       [0.93514936, 0.60943854, 0.24942038, 0.53296743, 0.5248156 ,
        0.94341148, 0.77370231, 0.08549907]])

In [129]:
 #? 2: randint() -> Generates random integers within a specified range
np.random.randint(3,10,size=(3,4))

array([[5, 3, 9, 8],
       [3, 9, 9, 5],
       [6, 5, 9, 5]], dtype=int32)

In [130]:
 #? 3: random() -> [0.0 to 1.0)
np.random.random((3,4))

array([[0.57262159, 0.12812918, 0.16559326, 0.39611955],
       [0.44249113, 0.46341093, 0.71341828, 0.77892003],
       [0.26667611, 0.76830901, 0.22702614, 0.46340028]])

In [131]:
 #! reshape() -> Used to change the shape of an array without changing the data
arr7=np.arange(1,13)
arr7.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [132]:
 #! flatten() -> Used to convert a multi dim array into 1Dim array
arr8=np.array([[1,2,3],[4,5,6]])
arr8.flatten()

array([1, 2, 3, 4, 5, 6])

In [133]:
 #! resize() -> Used to change the shape of an array
arr9=np.array([[1,2,3],[4,5,6]])
np.resize(arr9,(1,6,2))

array([[[1, 2],
        [3, 4],
        [5, 6],
        [1, 2],
        [3, 4],
        [5, 6]]])

In [134]:
arr10=np.random.randint(2,10,size=(3,4,5))
arr10

array([[[7, 7, 7, 8, 6],
        [7, 9, 8, 2, 9],
        [8, 3, 8, 5, 3],
        [5, 4, 9, 3, 5]],

       [[5, 2, 2, 9, 3],
        [5, 4, 7, 6, 4],
        [9, 4, 8, 3, 8],
        [2, 2, 3, 7, 3]],

       [[3, 7, 9, 5, 4],
        [9, 8, 7, 8, 4],
        [6, 6, 9, 2, 9],
        [3, 2, 4, 8, 5]]], dtype=int32)

In [135]:
arr11=np.random.randint(3,10,size=(3,4,5))
arr11

array([[[8, 7, 3, 7, 3],
        [6, 5, 8, 6, 3],
        [7, 9, 4, 8, 6],
        [5, 5, 7, 5, 6]],

       [[8, 3, 4, 9, 9],
        [4, 8, 9, 3, 8],
        [6, 9, 6, 7, 4],
        [8, 7, 3, 6, 6]],

       [[8, 3, 4, 4, 6],
        [6, 8, 4, 8, 4],
        [8, 8, 5, 4, 7],
        [8, 3, 5, 3, 3]]], dtype=int32)

In [136]:
 #! add()
sum=np.add(arr10,arr11)
sum

array([[[15, 14, 10, 15,  9],
        [13, 14, 16,  8, 12],
        [15, 12, 12, 13,  9],
        [10,  9, 16,  8, 11]],

       [[13,  5,  6, 18, 12],
        [ 9, 12, 16,  9, 12],
        [15, 13, 14, 10, 12],
        [10,  9,  6, 13,  9]],

       [[11, 10, 13,  9, 10],
        [15, 16, 11, 16,  8],
        [14, 14, 14,  6, 16],
        [11,  5,  9, 11,  8]]], dtype=int32)

In [137]:
 #! subtract()
sub=np.subtract(arr10,arr11)
sub

array([[[-1,  0,  4,  1,  3],
        [ 1,  4,  0, -4,  6],
        [ 1, -6,  4, -3, -3],
        [ 0, -1,  2, -2, -1]],

       [[-3, -1, -2,  0, -6],
        [ 1, -4, -2,  3, -4],
        [ 3, -5,  2, -4,  4],
        [-6, -5,  0,  1, -3]],

       [[-5,  4,  5,  1, -2],
        [ 3,  0,  3,  0,  0],
        [-2, -2,  4, -2,  2],
        [-5, -1, -1,  5,  2]]], dtype=int32)

In [138]:
diff1=np.subtract(arr11,arr10)
diff1

array([[[ 1,  0, -4, -1, -3],
        [-1, -4,  0,  4, -6],
        [-1,  6, -4,  3,  3],
        [ 0,  1, -2,  2,  1]],

       [[ 3,  1,  2,  0,  6],
        [-1,  4,  2, -3,  4],
        [-3,  5, -2,  4, -4],
        [ 6,  5,  0, -1,  3]],

       [[ 5, -4, -5, -1,  2],
        [-3,  0, -3,  0,  0],
        [ 2,  2, -4,  2, -2],
        [ 5,  1,  1, -5, -2]]], dtype=int32)

In [139]:
 #! divide()
quo=np.divide(arr10,arr11)
quo

array([[[0.875     , 1.        , 2.33333333, 1.14285714, 2.        ],
        [1.16666667, 1.8       , 1.        , 0.33333333, 3.        ],
        [1.14285714, 0.33333333, 2.        , 0.625     , 0.5       ],
        [1.        , 0.8       , 1.28571429, 0.6       , 0.83333333]],

       [[0.625     , 0.66666667, 0.5       , 1.        , 0.33333333],
        [1.25      , 0.5       , 0.77777778, 2.        , 0.5       ],
        [1.5       , 0.44444444, 1.33333333, 0.42857143, 2.        ],
        [0.25      , 0.28571429, 1.        , 1.16666667, 0.5       ]],

       [[0.375     , 2.33333333, 2.25      , 1.25      , 0.66666667],
        [1.5       , 1.        , 1.75      , 1.        , 1.        ],
        [0.75      , 0.75      , 1.8       , 0.5       , 1.28571429],
        [0.375     , 0.66666667, 0.8       , 2.66666667, 1.66666667]]])

In [140]:
 #! multiply()
mult=np.multiply(arr10,arr11)
mult

array([[[56, 49, 21, 56, 18],
        [42, 45, 64, 12, 27],
        [56, 27, 32, 40, 18],
        [25, 20, 63, 15, 30]],

       [[40,  6,  8, 81, 27],
        [20, 32, 63, 18, 32],
        [54, 36, 48, 21, 32],
        [16, 14,  9, 42, 18]],

       [[24, 21, 36, 20, 24],
        [54, 64, 28, 64, 16],
        [48, 48, 45,  8, 63],
        [24,  6, 20, 24, 15]]], dtype=int32)

In [141]:
 #! power()
pow=np.power(arr11,2)
pow

array([[[64, 49,  9, 49,  9],
        [36, 25, 64, 36,  9],
        [49, 81, 16, 64, 36],
        [25, 25, 49, 25, 36]],

       [[64,  9, 16, 81, 81],
        [16, 64, 81,  9, 64],
        [36, 81, 36, 49, 16],
        [64, 49,  9, 36, 36]],

       [[64,  9, 16, 16, 36],
        [36, 64, 16, 64, 16],
        [64, 64, 25, 16, 49],
        [64,  9, 25,  9,  9]]], dtype=int32)

In [142]:
 #! reciprocal() eg:1/n
x=np.array([5,6,7,8],dtype=float)
# x
rec=np.reciprocal(x)
rec


array([0.2       , 0.16666667, 0.14285714, 0.125     ])

In [143]:
 #! square()
np.square(rec)

array([0.04      , 0.02777778, 0.02040816, 0.015625  ])

In [144]:
 #! sqrt()
np.sqrt(rec)

array([0.4472136 , 0.40824829, 0.37796447, 0.35355339])

In [145]:
 #! sin(),cos(),tan()
np.sin(rec)

array([0.19866933, 0.16589613, 0.14237173, 0.12467473])

In [146]:
np.floor(quo)

array([[[0., 1., 2., 1., 2.],
        [1., 1., 1., 0., 3.],
        [1., 0., 2., 0., 0.],
        [1., 0., 1., 0., 0.]],

       [[0., 0., 0., 1., 0.],
        [1., 0., 0., 2., 0.],
        [1., 0., 1., 0., 2.],
        [0., 0., 1., 1., 0.]],

       [[0., 2., 2., 1., 0.],
        [1., 1., 1., 1., 1.],
        [0., 0., 1., 0., 1.],
        [0., 0., 0., 2., 1.]]])

In [147]:
np.ceil(quo)

array([[[1., 1., 3., 2., 2.],
        [2., 2., 1., 1., 3.],
        [2., 1., 2., 1., 1.],
        [1., 1., 2., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [2., 1., 1., 2., 1.],
        [2., 1., 2., 1., 2.],
        [1., 1., 1., 2., 1.]],

       [[1., 3., 3., 2., 1.],
        [2., 1., 2., 1., 1.],
        [1., 1., 2., 1., 2.],
        [1., 1., 1., 3., 2.]]])

In [148]:
np.round(quo)

array([[[1., 1., 2., 1., 2.],
        [1., 2., 1., 0., 3.],
        [1., 0., 2., 1., 0.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 0., 1., 0.],
        [1., 0., 1., 2., 0.],
        [2., 0., 1., 0., 2.],
        [0., 0., 1., 1., 0.]],

       [[0., 2., 2., 1., 1.],
        [2., 1., 2., 1., 1.],
        [1., 1., 2., 0., 1.],
        [0., 1., 1., 3., 2.]]])

In [149]:
 #! subsetting
#? 1D
a=np.array([1,2,3,4])
print(a[2])

3


In [150]:
a[1:]

array([2, 3, 4])

In [151]:
a[:3]

array([1, 2, 3])

In [152]:
a[:]

array([1, 2, 3, 4])

In [153]:
 #? Indexing in 2D
b=np.array([[1,2,3,4],[3,5,7,9]])
b

array([[1, 2, 3, 4],
       [3, 5, 7, 9]])

In [154]:
 #? [row,column]
b[1,2]

np.int64(7)

In [155]:
b[0,3]

np.int64(4)

In [156]:
c=np.array([
    (1,2,3,4,5),
    (2,3,4,5,6),
    (2,4,1,3,2),
    (3,5,4,2,0),
])

In [157]:
c[1]

array([2, 3, 4, 5, 6])

In [158]:
c[1:]

array([[2, 3, 4, 5, 6],
       [2, 4, 1, 3, 2],
       [3, 5, 4, 2, 0]])

In [159]:
c[1:,2]

array([4, 1, 4])

In [160]:
c[2:4,1:3]

array([[4, 1],
       [5, 4]])

In [161]:
 #? 3D
arrr=np.random.randint(2,10,size=(3,4,5))
arrr

array([[[4, 6, 6, 6, 4],
        [7, 5, 2, 2, 7],
        [3, 9, 9, 6, 3],
        [2, 5, 4, 5, 6]],

       [[6, 7, 4, 4, 9],
        [3, 9, 2, 5, 7],
        [2, 9, 4, 2, 6],
        [9, 9, 7, 9, 5]],

       [[2, 2, 2, 7, 4],
        [9, 8, 3, 5, 6],
        [2, 2, 9, 7, 7],
        [7, 8, 2, 9, 7]]], dtype=int32)

In [162]:
 #? ar_name[matrix,rows,col]
arrr[1,2,4]

np.int32(6)

In [163]:
arrr[1,2:4,1:]

array([[9, 4, 2, 6],
       [9, 7, 9, 5]], dtype=int32)

In [164]:
x=np.array([92,13,48,5])
# ascending
x.sort()
x

array([ 5, 13, 48, 92])

In [165]:
x[::-1]

array([92, 48, 13,  5])

In [166]:
y=np.array([[2,3,7,8],
            [12,0,5,4],
            ])
np.sort(y,axis=0)   # means sort each column separately.
#* axis=0 => col wise, axis=1 => row wise

array([[ 2,  0,  5,  4],
       [12,  3,  7,  8]])

In [167]:
np.sort(y,axis=1)

array([[ 2,  3,  7,  8],
       [ 0,  4,  5, 12]])

In [168]:
x=np.array([92,13,58,5])
np.max(x)

np.int64(92)

In [169]:
np.min(x)

np.int64(5)

In [170]:
np.min(y,axis=0)

array([2, 0, 5, 4])

In [171]:
np.max(y,axis=1)

array([ 8, 12])

In [172]:
 #! measures of central tendencies
#? mean -> average
# x1,x2,x3,x4
# mean=(x1+x2+x3+x4)/4

#? median
# (x2+x3)/2

#? mode -> most repeating values
# here mode=2

In [173]:
# find the mean of:
# 10,20,30,40,50
mean=30

# find the median of:
# 12,5,8,20,15
median=8

# find the mode of:
# 2,5,3,2,7,2,8,7
mode=2

In [174]:
m=np.array([[1,2,3],
            [4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [175]:
np.mean(m)

np.float64(3.5)

In [176]:
np.median(m)

np.float64(3.5)

In [177]:
np.mean(m,axis=1)

array([2., 5.])

In [178]:
 #? variance : Variance tells us how far the values are spread out from the mean
 #? standard deviation : Standard deviation is the square root of variance

In [179]:
aa=np.array([10,20,30,40,50])
np.var(aa)

np.float64(200.0)

In [180]:
np.std(aa)

np.float64(14.142135623730951)

In [181]:
# index of maximum value-argmax()
np.argmax(aa)

np.int64(4)

In [182]:
# index of minimum value-argmin()
np.argmin(aa)

np.int64(0)

In [183]:
 #! PERCENTILE -> Is used to understand the distribution and position of data by dividing the dataset into 100 parts.
# SCALING: 0 to 100
# 0th,25th,50th,75th,100th
p=np.array([10,20,30,40,50])
# finding the 50th percentile - (will be similar to the median value(centre point))
#? syntax: np.percentile(array, q)
np.percentile(p,50)  # Q2

np.float64(30.0)

In [184]:
# 0th percentile
np.percentile(p,0)

np.float64(10.0)

In [185]:
np.percentile(p,25) # Q1

np.float64(20.0)

In [186]:
np.percentile(p,75)   # Q3

np.float64(40.0)

In [187]:
np.percentile(p,100)   # MAXIMUM VALUE

np.float64(50.0)

In [188]:
 #! QUANTILE
# SCALING: 0 to 1

np.quantile(p,0.5)

np.float64(30.0)

In [189]:
 #! OUTLIERS -> An outlier is a data value that is very different from the other values in a dataset.
# ---------------
#* eg: consider the age of students
# age=[19,22,26,200,28,32,8]
#* Here, 200 and 8 looks like an outlier because most ages are between 19 and 32, while 200 is much higher and 8 is much lower.
#* while calculating means we also consider these outlier points


#! IQR METHOD(INTER QUARTILE RANGE) -> METHODS TO DETECT OUTLIERS
# ----------
#! IQR=Q3-Q1
#! UPPER BOUND=Q3 + 1.5 * IQR
#! LOWER BOUND=Q1 - 1.5 * IQR

In [190]:
age=np.array([19,22,26,200,28,32,5])
Q1=np.percentile(age,25)
Q3=np.percentile(age,75)
IQR=Q3-Q1

In [191]:
lower=Q1-1.5*IQR
lower

np.float64(6.25)

In [192]:
upper=Q3+1.5*IQR
upper

np.float64(44.25)

In [193]:
outliers=age[(age>upper)|(age<lower)]
outliers

array([200,   5])

In [194]:
 #! REMOVE OUTLIERS
new_age=age[(age>=lower) & (age<=upper)]
new_age

array([19, 22, 26, 28, 32])

In [195]:
 #! REPLACING WITH MEDIAN,MEAN
#! CAPPING METHOD -> REPLACING EXTREME VALUES WITH BOUNDARY VALUES
#?syntax: np.clip(array, lower_limit, upper_limit)
age=np.clip(age,5,45)
age

array([19, 22, 26, 45, 28, 32,  5])

In [196]:
 #! COVARIANCE -> Covariance tells whether two variables increase/decrease together or move in opposite directions.
#! COVARIANCE=COV(X,Y)=∑(Xi−Xˉ)(Yi​−Yˉ)/n-1

#! CORRELATION=COV(X,Y)/STD(X)*STD(Y)

In [197]:
x=np.array([10,20,30,40])
y=np.array([15,25,35,45])
np.cov(x,y)

#* np.cov() returns a covariance matrix:
#* [[cov(x,x), cov(x,y)],
#*  [cov(y,x), cov(y,y)]]


array([[166.66666667, 166.66666667],
       [166.66666667, 166.66666667]])

In [198]:
 #! To return the covariance btw x and y put [0,1]
np.cov(x,y)[0,1]

np.float64(166.66666666666666)

In [199]:
 #! CORRELATION -1 TO 1
#* when correlation>0 to 1 -> positive correlation
#* when correlation=0 -> no linear correlation
#* when correlation<0 to -1 -> negative orrelation
np.corrcoef(x,y)[0,1]

np.float64(1.0)